### ISSUE TITLE
in `readlines': no implicit conversion of Array into String (TypeError)

### ISSUE THREAD

**Issue by kannes** [pachacamac/stimmung#1]
I have no idea what I am doing. Not a ruby user or anything. I put your example code in a file called test.rb and installed stimmung via gem. I use ruby 2.2.2p95. If I try to run it, this happens:

```
$ ruby test.rb 
/home/me/.gem/ruby/2.2.0/gems/stimmung-0.0.1/lib/stimmung.rb:19:in `readlines': no implicit conversion of Array into String (TypeError)
    from /home/me/.gem/ruby/2.2.0/gems/stimmung-0.0.1/lib/stimmung.rb:19:in `block in load_dictionary'
    from /home/me/.gem/ruby/2.2.0/gems/stimmung-0.0.1/lib/stimmung.rb:18:in `each'
    from /home/me/.gem/ruby/2.2.0/gems/stimmung-0.0.1/lib/stimmung.rb:18:in `load_dictionary'
    from /home/me/.gem/ruby/2.2.0/gems/stimmung-0.0.1/lib/stimmung.rb:9:in `initialize'
    from test.rb:6:in `new'
    from test.rb:6:in `<main>'
```

**Comment by pachacamac** [comment]
You gave it an Array instead of a String I think. But I'd need to see your test.rb in order to help you

**Comment by kannes** [comment]
It's identical to your example, just with the require on top:

```
require 'stimmung'

# use this to init with the default dictionaries
stimmung = Stimmung.new

# or this to init with your dictionaries
stimmung = Stimmung.new('my_dict1.txt', 'my_dict2.txt', '...')

# you can always load additional dictionaries later on with
stimmung.load_dictionary('my_dict.txt')

# and to get an analysis you just do
stimmung.score('irgendein toller text')
# => 0.5066 

# this score will be between -1 (super negative) and 1 (super positive)
```

**Comment by kannes** [comment]
oh wait...

**Comment by kannes** [comment]
```
require 'stimmung'
stimmung = Stimmung.new('german.txt') # i copied it to ./
puts stimmung.score('hurra es funktioniert das ist toll')
```

or 

```
require 'stimmung'
stimmung = Stimmung.new('~/.gem/ruby/2.2.0/gems/stimmung-0.0.1/lib/german.txt')
puts stimmung.score('hurra es funktioniert das ist toll')
```

both give me that error.

If I use

```
stimmung = Stimmung.new()
```

it works fine

**Comment by pachacamac** [comment]
I found the error. It was a missing star in the initializer :smile: fixed, added a test, published new gem version.
Make sure to run `bundle update stimmmung` or `gem update stimmung`

Thanks for reporting! :+1:

**Comment by kannes** [comment]
Thanks!
